export default data = {
  siderBarNames: {},
  TypeOfInsp:[
    { label: "Routine", value: "Routine"},
    { label: "Information/Complaint", value: "Information/Complaint"},
    { label: "Follow Up", value: "Follow Up"},
    { label: "Compliance/Assistance", value: "Compliance/Assistance"},
    { label: "EIA/Audit", value: "EIA/Audit"},
    { label: "Restoration", value: "Restoration"},
    { label: "Demarcation", value: "Demarcation" }
  ],
  permitsList: [
    { label: "BUL501757/2GWJDW 2013", value: "1" },
    { label: "BUL501757/2GWJDX 2013", value: "2" },
    { label: "BUL501757/2GWJDY 2013", value: "3" },
    { label: "BUL501757/2GWJDZ 2013", value: "4" },
    { label: "BUL501758/2GWJDR 2013", value: "5" },
    { label: "BUL501752/2GWJDA 2013", value: "6" },
    { label: "BUL501756/2GWJDB 2013", value: "7" },
    { label: "BUL501759/2GWJDC 2013", value: "8" },
  ],
  quarterList: [
    { label: "Q1 - Jul to Sept", value: "1" },
    { label: "Q2 - Oct to Dec", value: "2" },
    { label: "Q3 - Jan to Mar", value: "3" },
    { label: "Q4 - Apr to Jun", value: "4" },
  ],
  DashData:[
    {
      planId: '1',
      activity: 'Activity 1',
      startDate: '2023-07-01',
      endDate: '2023-07-10',
      monitoring: 'Monitoring 1',
      observation: 'Observation 1',
    },
    {
      planId: '2',
      activity: 'Activity 2',
      startDate: '2023-05-04',
      endDate: '2023-08-10',
      monitoring: 'Monitoring 2',
      observation: 'Observation 2',
    },
    {
      planId: '3',
      activity: 'Activity 3',
      startDate: '2023-09-15',
      endDate: '2023-09-25',
      monitoring: 'Monitoring 3',
      observation: 'Observation 3',
    },
    {
      planId: '4',
      activity: 'Activity 4',
      startDate: '2023-06-10',
      endDate: '2023-06-20',
      monitoring: 'Monitoring 4',
      observation: 'Observation 4',
    },
    {
      planId: '5',
      activity: 'Activity 5',
      startDate: '2023-11-01',
      endDate: '2023-11-15',
      monitoring: 'Monitoring 5',
      observation: 'Observation 5',
    },
    {
      planId: '6',
      activity: 'Activity 6',
      startDate: '2023-07-20',
      endDate: '2023-07-30',
      monitoring: 'Monitoring 6',
      observation: 'Observation 6',
    },
    {
      planId: '7',
      activity: 'Activity 7',
      startDate: '2023-08-15',
      endDate: '2023-08-25',
      monitoring: 'Monitoring 7',
      observation: 'Observation 7',
    },
    {
      planId: '8',
      activity: 'Activity 8',
      startDate: '2023-10-05',
      endDate: '2023-10-15',
      monitoring: 'Monitoring 8',
      observation: 'Observation 8',
    },
    {
      planId: '9',
      activity: 'Activity 9',
      startDate: '2023-04-10',
      endDate: '2023-04-20',
      monitoring: 'Monitoring 9',
      observation: 'Observation 9',
    },
    {
      planId: '10',
      activity: 'Activity 10',
      startDate: '2023-12-01',
      endDate: '2023-12-10',
      monitoring: 'Monitoring 10',
      observation: 'Observation 10',
    },
  ],
 planData : [
    {
      planId: 1,
      activity: 'Activity 1',
      WetlandName: 'Kitambago-Kadama ',
      Region: 'Eastern',
      District: 'Bugiri',
      Wetlandcode: '0403900703200',
      County: 'Bukooli',
      Subcounty: 'Buwunga',
      Parish: 'Nsono',
      Eastings: '578642.641447',
      Northings: '58028.4056611',
      Actions: 'Inspection',
    },
    {
      planId: 1,
      activity: 'Activity 2',
      WetlandName: 'Lake Victoria ',
      Region: 'Northern',
      District: 'Gulu',
      Wetlandcode: '0403900703201',
      County: 'County 2',
      Subcounty: 'Subcounty 2',
      Parish: 'Parish 2',
      Eastings: '123456.789',
      Northings: '987654.321',
      Actions: 'Inspection',
    },
    {
      planId: 3,
      activity: 'Activity 3',
      WetlandName: 'Kigezi ',
      Region: 'Western',
      District: 'Kabale',
      Wetlandcode: '0403900703202',
      County: 'County 3',
      Subcounty: 'Subcounty 3',
      Parish: 'Parish 3',
      Eastings: '987654.321',
      Northings: '123456.789',
      Actions: 'Inspection',
    },
    {
      planId: 4,
      activity: 'Activity 4',
      WetlandName: 'Kampala ',
      Region: 'Central',
      District: 'Kampala',
      Wetlandcode: '0403900703203',
      County: 'County 4',
      Subcounty: 'Subcounty 4',
      Parish: 'Parish 4',
      Eastings: '456789.123',
      Northings: '321654.987',
      Actions: 'Inspection',
    },
    {
      planId: 5,
      activity: 'Activity 5',
      WetlandName: 'Mount Elgon ',
      Region: 'Eastern',
      District: 'Mbale',
      Wetlandcode: '0403900703204',
      County: 'County 5',
      Subcounty: 'Subcounty 5',
      Parish: 'Parish 5',
      Eastings: '741852.963',
      Northings: '852963.741',
      Actions: 'Inspection',
    },
    {
      planId: 6,
      activity: 'Activity 6',
      WetlandName: 'Acholi ',
      Region: 'Northern',
      District: 'Lira',
      Wetlandcode: '0403900703205',
      County: 'County 6',
      Subcounty: 'Subcounty 6',
      Parish: 'Parish 6',
      Eastings: '369852.147',
      Northings: '258963.741',
      Actions: 'Inspection',
    },
    {
      planId: 7,
      activity: 'Activity 7',
      WetlandName: 'Mbarara ',
      Region: 'Western',
      District: 'Mbarara',
      Wetlandcode: '0403900703206',
      County: 'County 7',
      Subcounty: 'Subcounty 7',
      Parish: 'Parish 7',
      Eastings: '741258.963',
      Northings: '369852.147',
      Actions: 'Inspection',
    },
    {
      planId: 8,
      activity: 'Activity 8',
      WetlandName: 'Kiboga ',
      Region: 'Central',
      District: 'Kiboga',
      Wetlandcode: '0403900703207',
      County: 'County 8',
      Subcounty: 'Subcounty 8',
      Parish: 'Parish 8',
      Eastings: '852963.741',
      Northings: '741258.963',
      Actions: 'Inspection',
    },
    {
      planId: 9,
      activity: 'Activity 9',
      WetlandName: 'Soroti ',
      Region: 'Eastern',
      District: 'Soroti',
      Wetlandcode: '0403900703208',
      County: 'County 9',
      Subcounty: 'Subcounty 9',
      Parish: 'Parish 9',
      Eastings: '963741.852',
      Northings: '963741.852',
      Actions: 'Inspection',
    },
    {
      planId: 10,
      activity: 'Activity 10',
      WetlandName: 'Kitgum ',
      Region: 'Northern',
      District: 'Kitgum',
      Wetlandcode: '0403900703209',
      County: 'County 10',
      Subcounty: 'Subcounty 10',
      Parish: 'Parish 10',
      Eastings: '147258.369',
      Northings: '147258.369',
      Actions: 'Inspection',
    },
  ],
   dropdownData :{
    regions: [
      'Region A',
      'Region B',
      'Region C',
      'Region D',
      'Region E',
      'Region F',
      'Region G',
      'Region H',
      'Region I',
      'Region J',
      'Region K',
      'Region L',
      'Region M',
      'Region N',
      'Region O',
      'Region P',
      'Region Q',
      'Region R',
      'Region S',
      'Region T',
    ],
    districts: [
      'District X',
      'District Y',
      'District Z',
      'District W',
      'District V',
      'District U',
      'District T',
      'District S',
      'District R',
      'District Q',
      'District P',
      'District O',
      'District N',
      'District M',
      'District L',
      'District K',
      'District J',
      'District I',
      'District H',
      'District G',
    ],
    countries: [
      'Country Alpha',
      'Country Beta',
      'Country Gamma',
      'Country Delta',
      'Country Epsilon',
      'Country Zeta',
      'Country Eta',
      'Country Theta',
      'Country Iota',
      'Country Kappa',
      'Country Lambda',
      'Country Mu',
      'Country Nu',
      'Country Xi',
      'Country Omicron',
      'Country Pi',
      'Country Rho',
      'Country Sigma',
      'Country Tau',
      'Country Upsilon',
    ],
    subCountries: [
      'SubCountry One',
      'SubCountry Two',
      'SubCountry Three',
      'SubCountry Four',
      'SubCountry Five',
      'SubCountry Six',
      'SubCountry Seven',
      'SubCountry Eight',
      'SubCountry Nine',
      'SubCountry Ten',
      'SubCountry Eleven',
      'SubCountry Twelve',
      'SubCountry Thirteen',
      'SubCountry Fourteen',
      'SubCountry Fifteen',
      'SubCountry Sixteen',
      'SubCountry Seventeen',
      'SubCountry Eighteen',
      'SubCountry Nineteen',
      'SubCountry Twenty',
    ],
    parishes: [
      'Parish A',
      'Parish B',
      'Parish C',
      'Parish D',
      'Parish E',
      'Parish F',
      'Parish G',
      'Parish H',
      'Parish I',
      'Parish J',
      'Parish K',
      'Parish L',
      'Parish M',
      'Parish N',
      'Parish O',
      'Parish P',
      'Parish Q',
      'Parish R',
      'Parish S',
      'Parish T',
    ],
  }  
  
}